// Stash Extension Configuration
// Generated by deploy.js
const CONFIG = {
  SUPABASE_URL: 'https://ddxqibrddfakxdhhnmyo.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkeHFpYnJkZGZha3hkaGhubXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3MzQzMzQsImV4cCI6MjA4NDMxMDMzNH0.062-04Q1CoqQj2-fQXsZ5bwVCNq3bq7cvrhAqyUABYg',
  WEB_APP_URL: 'http://localhost:8000',
  USER_ID: 'aa623301-c1af-4c37-8e3f-189bf8a0100d',
};
if (typeof module !== 'undefined') {
  module.exports = CONFIG;
}