const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function main() {
    console.log('\n🚀 Stash Configuration Wizard\n');
    console.log('This script will help you configure Stash for your environment.');
    console.log('You will need your Supabase Project URL, Anon Key, and User ID.\n');

    const supabaseUrl = await question('Enter Supabase URL (e.g., https://xyz.supabase.co): ');
    const supabaseKey = await question('Enter Supabase Anon Key: ');
    const userId = await question('Enter Supabase User ID (UUID): ');
    const webAppUrl = await question('Enter Web App URL (e.g. http://localhost:3000 or your Vercel URL): ');

    // Update Web Config
    const webConfigPath = path.join(__dirname, 'web', 'config.js');
    const webConfigContent = `// Stash Web App Configuration
// Generated by configure.js

const CONFIG = {
  // Your Supabase project URL
  SUPABASE_URL: '${supabaseUrl.trim()}',

  // Your Supabase anon/public key
  SUPABASE_ANON_KEY: '${supabaseKey.trim()}',

  // Your user ID from Supabase
  USER_ID: '${userId.trim()}',
};
`;

    fs.writeFileSync(webConfigPath, webConfigContent);
    console.log('✅ Updated web/config.js');

    // Update Extension Config
    const extConfigPath = path.join(__dirname, 'extension', 'config.js');
    const extConfigContent = `// Stash Configuration
// Generated by configure.js

const CONFIG = {
  // Your Supabase project URL
  SUPABASE_URL: '${supabaseUrl.trim()}',

  // Your Supabase anon/public key
  SUPABASE_ANON_KEY: '${supabaseKey.trim()}',

  // Your web app URL
  WEB_APP_URL: '${webAppUrl.trim()}',

  // Your user ID from Supabase
  USER_ID: '${userId.trim()}',
};

// Don't edit below this line
if (typeof module !== 'undefined') {
  module.exports = CONFIG;
}
`;

    fs.writeFileSync(extConfigPath, extConfigContent);
    console.log('✅ Updated extension/config.js');

    console.log('\n🎉 Configuration complete!');
    console.log('\nNext steps:');
    console.log('1. Run the database schema in Supabase SQL Editor if you haven\'t already.');
    console.log('2. Load the \'extension\' folder in Chrome.');
    console.log('3. Deploy the \'web\' folder or run it locally.\n');

    rl.close();
}

main();
