const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

// Minimal .env parser
function loadEnv() {
    const envPath = path.join(__dirname, '.env');
    if (fs.existsSync(envPath)) {
        const lines = fs.readFileSync(envPath, 'utf8').split('\n');
        lines.forEach(line => {
            const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
            if (match) {
                const key = match[1];
                let value = match[2] || '';
                // Remove quotes if present
                if (value.length > 0 && value.charAt(0) === '"' && value.charAt(value.length - 1) === '"') {
                    value = value.substring(1, value.length - 1);
                }
                process.env[key] = value;
            }
        });
        return true;
    }
    return false;
}

loadEnv();

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function run(cmd) {
    console.log(`\n> Running: ${cmd}`);
    // Pass current environment (including possible access token from .env)
    const env = { ...process.env };
    try {
        return execSync(cmd, { stdio: 'inherit', env });
    } catch (e) {
        console.error(`Error running command: ${cmd}`);
        if (cmd.includes('supabase link') && !process.env.SUPABASE_ACCESS_TOKEN) {
            console.log('\n💡 Tip: It looks like you need to log in. Try "npx supabase login" or add "SUPABASE_ACCESS_TOKEN" to your .env file.');
        }
        process.exit(1);
    }
}

async function main() {
    console.log('\n🌟 Stash "Zen" Automated Deployer\n');
    if (fs.existsSync('.env')) {
        console.log('📝 .env file detected and loaded.\n');
    }

    const mode = await question('Deploy to (L)ocal or (C)loud? [L/c]: ') || 'L';

    if (mode.toUpperCase() === 'L') {
        console.log('\n--- Local Setup ---');
        console.log('Ensure Docker is running.');
        await run('npx supabase start');

        // Get status for local keys
        const status = execSync('npx supabase status', { encoding: 'utf8' });
        const urlMatch = status.match(/API URL: (.*)/);
        const keyMatch = status.match(/anon key: (.*)/);

        if (urlMatch && keyMatch) {
            updateConfigs(urlMatch[1].trim(), keyMatch[1].trim(), 'local-user');
            console.log('\n✅ Local Supabase is running and configured!');
        }
    } else {
        console.log('\n--- Cloud Setup ---');

        const projectRef = process.env.SUPABASE_PROJECT_ID || await question('Enter your Supabase Project ID: ');

        await run(`npx supabase link --project-ref ${projectRef} --yes`);

        console.log('\nPushing database schema...');
        await run('npx supabase db push --yes');

        console.log('\nDeploying Edge Functions...');
        await run('npx supabase functions deploy fetch-url --no-verify-jwt --yes');
        await run('npx supabase functions deploy send-digest --yes');

        let url = process.env.SUPABASE_URL || `https://${projectRef}.supabase.co`;

        // Cleanup: If the user pasted a dashboard link, convert it to an API link
        if (url.includes('supabase.com/dashboard')) {
            url = `https://${projectRef}.supabase.co`;
            console.log(`\n💡 Note: Converted dashboard link to API link: ${url}`);
        }

        const key = process.env.SUPABASE_ANON_KEY || await question(`Enter your "anon" public key for ${url}: `);
        const userId = process.env.USER_ID || await question('Enter your User ID: ');

        // Handle Resend if key exists
        if (process.env.RESEND_API_KEY) {
            console.log('\nSetting up Resend API key...');
            await run(`npx supabase secrets set RESEND_API_KEY=${process.env.RESEND_API_KEY}`);
        }

        updateConfigs(url, key, userId);
        console.log('\n✅ Cloud Supabase is configured!');
    }

    console.log('\n🚀 Next Step: Run "cd web && python3 -m http.server 8000" and visit http://localhost:8000');
    rl.close();
}

function updateConfigs(url, key, userId) {
    const webConfig = `// Stash Web App Configuration
// Generated by deploy.js
const CONFIG = {
  SUPABASE_URL: '${url}',
  SUPABASE_ANON_KEY: '${key}',
  USER_ID: '${userId}',
};`;

    const extConfig = `// Stash Extension Configuration
// Generated by deploy.js
const CONFIG = {
  SUPABASE_URL: '${url}',
  SUPABASE_ANON_KEY: '${key}',
  WEB_APP_URL: 'http://localhost:8000',
  USER_ID: '${userId}',
};
if (typeof module !== 'undefined') {
  module.exports = CONFIG;
}`;

    fs.writeFileSync(path.join(__dirname, 'web', 'config.js'), webConfig);
    fs.writeFileSync(path.join(__dirname, 'extension', 'config.js'), extConfig);
    console.log('📝 config.js files updated for both Web and Extension!');
}

main();
